import ExcelJS from 'exceljs';
import type {
  Border,
  Cell,
  Fill,
  Workbook,
  Worksheet,
} from 'exceljs';
import {
  CATALOG_CANONICALIZATION_REVISION,
  CATALOG_EXPORT_APP_NAME,
  CATALOG_EXPORT_DOCUMENT_TITLE,
  CATALOG_EXPORT_SPEC_REVISION,
  type CatalogExportChangeActionCounts,
  type CatalogExportDataset,
  type CatalogExportRow,
  verificationSheetHeaders,
} from './data';

const DEFAULT_FONT = 'TH Sarabun New';
const MONEY_FORMAT = '#,##0.00';
const HEADER_FILL: Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFFD100' },
};
const SUBTLE_FILL: Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFF7F7F7' },
};
const DRAFT_FILL: Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FFFFE4E6' },
};
const THIN_BORDER: Partial<Border> = { style: 'thin', color: { argb: 'FFD4D4D4' } };
const ALL_BORDERS = {
  top: THIN_BORDER,
  left: THIN_BORDER,
  bottom: THIN_BORDER,
  right: THIN_BORDER,
};

export async function buildCatalogExportWorkbookBuffer(
  dataset: CatalogExportDataset,
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = CATALOG_EXPORT_APP_NAME;
  workbook.lastModifiedBy = CATALOG_EXPORT_APP_NAME;
  workbook.created = dataset.exportedAt;
  workbook.modified = dataset.exportedAt;
  workbook.subject = `Master Catalog ${dataset.version.versionString}`;
  workbook.title = CATALOG_EXPORT_DOCUMENT_TITLE;
  workbook.description = `Dataset hash: ${dataset.canonicalDatasetHash}`;
  workbook.company = 'National Telecom Public Company Limited';

  createDocumentInfoSheet(workbook, dataset);
  createPriceListSheet(workbook, dataset);
  createDictionarySheet(workbook, dataset);
  createChangeSummarySheet(workbook, dataset);
  createVerificationSheet(workbook, dataset);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

function createDocumentInfoSheet(workbook: Workbook, dataset: CatalogExportDataset) {
  const sheet = workbook.addWorksheet('ข้อมูลเอกสาร', {
    pageSetup: portraitPageSetup(),
    properties: { tabColor: { argb: 'FFFFD100' } },
  });

  sheet.columns = [
    { width: 34 },
    { width: 92 },
  ];
  sheet.views = [{ state: 'frozen', ySplit: 4 }];

  let rowIndex = 1;
  sheet.mergeCells(rowIndex, 1, rowIndex, 2);
  const title = sheet.getCell(rowIndex, 1);
  title.value = CATALOG_EXPORT_DOCUMENT_TITLE;
  title.font = font({ bold: true, size: 18 });
  title.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
  rowIndex += 1;

  if (dataset.isDraftExport) {
    sheet.mergeCells(rowIndex, 1, rowIndex, 2);
    const draft = sheet.getCell(rowIndex, 1);
    draft.value = 'DRAFT – ห้ามใช้อ้างอิง';
    draft.font = font({ bold: true, size: 16, color: 'FFB91C1C' });
    draft.fill = DRAFT_FILL;
    draft.alignment = { horizontal: 'center', vertical: 'middle' };
    rowIndex += 1;
  }

  rowIndex += 1;
  const rows: Array<[string, string]> = [
    ['Document purpose', 'Official Master Catalog reference export generated from the selected database version'],
    ['Organization', 'บริษัท โทรคมนาคมแห่งชาติ จำกัด (มหาชน)'],
    ['Catalog version', dataset.version.versionString],
    ['Version name', dataset.version.name],
    ['Publication status', displayStatus(dataset)],
    ['Current Default', dataset.version.isCurrentDefault ? 'Yes' : 'No'],
    ['Effective date', displayDateWithIso(dataset.version.effectiveDate)],
    ['Approval reference', dataset.version.approvalReference ?? '-'],
    ['Approval document date', displayDateWithIso(dataset.version.approvalDocumentDate)],
    ['Published at/by', displayPublishedStamp(dataset)],
    ['Exported at/by', `${formatThaiDateTime(dataset.exportedAtIso)} / ${dataset.exportedBy.displayName}`],
    ['Base version', dataset.version.basedOnVersionString ?? '-'],
    ['Item count covered by dataset hash', dataset.counts.rowCount.toLocaleString('th-TH')],
    ['Active / inactive rows', `${dataset.counts.activeRows.toLocaleString('th-TH')} / ${dataset.counts.inactiveRows.toLocaleString('th-TH')}`],
    ['Dataset SHA-256', dataset.canonicalDatasetHash],
    ['Verification instructions', 'Reconstruct UTF-8 "[" + ข้อมูลตรวจสอบ._canonical_row_json joined with "," + "]\\n"; SHA-256 must match the dataset hash above.'],
    ['Canonicalization contract revision', CATALOG_CANONICALIZATION_REVISION],
    ['Export specification revision', CATALOG_EXPORT_SPEC_REVISION],
    ['Generated by', CATALOG_EXPORT_APP_NAME],
    ['Factor F / BOQ inclusion', 'Excluded from this Master Catalog dataset, hash, count, and workbook'],
    ['Binary file hash note', 'Binary SHA-256 is calculated after saving/filing and is recorded outside this workbook.'],
  ];

  for (const [key, value] of rows) {
    sheet.getCell(rowIndex, 1).value = key;
    sheet.getCell(rowIndex, 2).value = safeText(value);
    styleKeyValueRow(sheet, rowIndex);
    rowIndex += 1;
  }

  if (!dataset.isOfficialPublishedExport) {
    sheet.getCell(rowIndex, 1).value = 'Draft dataset hash';
    sheet.getCell(rowIndex, 2).value = 'Draft dataset hash - not an official publication hash';
    styleKeyValueRow(sheet, rowIndex, DRAFT_FILL);
  }
}

function createPriceListSheet(workbook: Workbook, dataset: CatalogExportDataset) {
  const sheet = workbook.addWorksheet('รายการราคา', {
    pageSetup: landscapePageSetup(),
    properties: { tabColor: { argb: 'FFFFD100' } },
  });

  sheet.columns = [
    { width: 9 },
    { width: 18 },
    { width: 64 },
    { width: 10 },
    { width: 16 },
    { width: 16 },
    { width: 18 },
    { width: 28 },
    { width: 16 },
    { width: 28 },
    { width: 16 },
    { width: 28 },
    { width: 12 },
  ];
  sheet.views = [{ state: 'frozen', ySplit: 3 }];

  let rowIndex = 1;
  sheet.mergeCells(rowIndex, 1, rowIndex, 13);
  sheet.getCell(rowIndex, 1).value =
    dataset.isDraftExport
      ? `DRAFT – ห้ามใช้อ้างอิง | ${CATALOG_EXPORT_DOCUMENT_TITLE}`
      : CATALOG_EXPORT_DOCUMENT_TITLE;
  sheet.getCell(rowIndex, 1).font = font({ bold: true, size: 16 });
  sheet.getCell(rowIndex, 1).alignment = { horizontal: 'center', vertical: 'middle' };
  rowIndex += 1;

  sheet.mergeCells(rowIndex, 1, rowIndex, 13);
  sheet.getCell(rowIndex, 1).value =
    `v${dataset.version.versionString} | ${displayStatus(dataset)} | count ${dataset.counts.rowCount.toLocaleString('th-TH')} | ${dataset.canonicalDatasetHash}`;
  sheet.getCell(rowIndex, 1).font = font({ size: 12 });
  sheet.getCell(rowIndex, 1).alignment = { horizontal: 'center', vertical: 'middle' };
  rowIndex += 1;

  const headerRow = rowIndex;
  const headers = [
    'ลำดับ',
    'รหัสรายการ',
    'รายการ',
    'หน่วย',
    'ค่าวัสดุ (บาท)',
    'ค่าแรง (บาท)',
    'ราคาต่อหน่วย (บาท)',
    'หมวดหมู่',
    'รหัสบริบทงาน',
    'บริบทงาน',
    'รหัสชนิดรายการ',
    'ชนิดรายการ',
    'สถานะ',
  ];
  headers.forEach((header, index) => {
    const cell = sheet.getCell(headerRow, index + 1);
    cell.value = header;
    applyHeaderCellStyle(cell);
  });
  rowIndex += 1;

  for (const row of dataset.rows) {
    writePriceRow(sheet, rowIndex, row);
    rowIndex += 1;
  }

  sheet.autoFilter = {
    from: { row: headerRow, column: 1 },
    to: { row: headerRow, column: headers.length },
  };
  sheet.pageSetup.printTitlesRow = `${headerRow}:${headerRow}`;
  setFooter(sheet, dataset);
}

function createDictionarySheet(workbook: Workbook, dataset: CatalogExportDataset) {
  const sheet = workbook.addWorksheet('พจนานุกรมรหัส', {
    pageSetup: landscapePageSetup(),
    properties: { tabColor: { argb: 'FF005BBB' } },
  });
  sheet.columns = [
    { width: 18 },
    { width: 32 },
    { width: 32 },
    { width: 18 },
    { width: 32 },
    { width: 32 },
    { width: 20 },
    { width: 28 },
  ];
  writeHeaderRow(sheet, 1, [
    'รหัสบริบทงาน',
    'ชื่อบริบทงาน (ไทย)',
    'Work Context Name (English)',
    'รหัสชนิดรายการ',
    'ชื่อชนิดรายการ (ไทย)',
    'Item Type Name (English)',
    'จำนวนรายการในเวอร์ชัน',
    'หมายเหตุที่อนุมัติ',
  ]);

  dataset.dictionaryRows.forEach((row, index) => {
    const rowIndex = index + 2;
    const values = [
      row.workContextCode,
      row.workContextNameTh,
      row.workContextNameEn ?? '',
      row.itemTypeCode,
      row.itemTypeNameTh,
      row.itemTypeNameEn ?? '',
      row.itemCount,
      row.note,
    ];
    values.forEach((value, columnIndex) => {
      const cell = sheet.getCell(rowIndex, columnIndex + 1);
      cell.value = typeof value === 'number' ? value : safeText(value);
      cell.font = font();
      cell.alignment = {
        vertical: 'top',
        horizontal: columnIndex === 6 ? 'right' : 'left',
        wrapText: true,
      };
      cell.border = ALL_BORDERS;
    });
  });

  sheet.views = [{ state: 'frozen', ySplit: 1 }];
  sheet.autoFilter = 'A1:H1';
  sheet.pageSetup.printTitlesRow = '1:1';
  setFooter(sheet, dataset);
}

function createChangeSummarySheet(workbook: Workbook, dataset: CatalogExportDataset) {
  const sheet = workbook.addWorksheet('สรุปการเปลี่ยนแปลง', {
    pageSetup: landscapePageSetup(),
    properties: { tabColor: { argb: 'FF4D4D4D' } },
  });
  sheet.columns = [
    { width: 24 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 18 },
    { width: 44 },
    { width: 24 },
    { width: 24 },
    { width: 28 },
    { width: 28 },
    { width: 28 },
  ];

  sheet.mergeCells(1, 1, 1, 12);
  sheet.getCell(1, 1).value = 'สรุปการเปลี่ยนแปลง';
  sheet.getCell(1, 1).font = font({ bold: true, size: 16 });
  sheet.getCell(1, 1).alignment = { horizontal: 'center' };

  const totalCounts = totalActionCounts(dataset);
  const metadataRows: Array<[string, string]> = [
    ['Catalog version', dataset.version.versionString],
    ['Base version', dataset.version.basedOnVersionString ?? '-'],
    ['Approval reference', dataset.version.approvalReference ?? '-'],
    ['Counts add/update/retire/recode', `${totalCounts.add}/${totalCounts.update}/${totalCounts.retire}/${totalCounts.recode}`],
    ['History note', 'Full row history remains in the system. Raw old/new JSON and rejected workbook contents are not included in this workbook.'],
  ];

  let rowIndex = 3;
  for (const [key, value] of metadataRows) {
    sheet.getCell(rowIndex, 1).value = key;
    sheet.getCell(rowIndex, 2).value = safeText(value);
    sheet.mergeCells(rowIndex, 2, rowIndex, 12);
    styleKeyValueRow(sheet, rowIndex);
    rowIndex += 1;
  }

  rowIndex += 1;
  writeHeaderRow(sheet, rowIndex, [
    'Change-set source',
    'Add',
    'Update',
    'Retire',
    'Recode',
    'Created at',
    'Reason',
    'Actor display name',
    'Import source basename',
    'Import source SHA-256',
    'Archive reference',
    'Lock version before/after',
  ]);
  const headerRow = rowIndex;
  rowIndex += 1;

  if (dataset.changeSummaryScope === 'limited') {
    sheet.getCell(rowIndex, 1).value = 'limited';
    sheet.getCell(rowIndex, 2).value =
      'Detailed change-set history is available to active admins in the system.';
    sheet.mergeCells(rowIndex, 2, rowIndex, 12);
    styleDataRow(sheet, rowIndex, 12);
  } else if (dataset.changeSets.length === 0) {
    sheet.getCell(rowIndex, 1).value = 'none';
    sheet.getCell(rowIndex, 2).value = 'No version-scoped change set is available.';
    sheet.mergeCells(rowIndex, 2, rowIndex, 12);
    styleDataRow(sheet, rowIndex, 12);
  } else {
    for (const changeSet of dataset.changeSets) {
      const values = [
        changeSet.changeType,
        changeSet.itemActionCounts.add,
        changeSet.itemActionCounts.update,
        changeSet.itemActionCounts.retire,
        changeSet.itemActionCounts.recode,
        formatThaiDateTime(changeSet.createdAt),
        changeSet.reason,
        changeSet.actorDisplayName,
        changeSet.importSourceFilename ?? '',
        changeSet.importSourceFileSha256 ?? '',
        changeSet.importArchiveReference ?? '',
        `${changeSet.beforeLockVersion ?? '-'} / ${changeSet.afterLockVersion ?? '-'}`,
      ];

      values.forEach((value, columnIndex) => {
        const cell = sheet.getCell(rowIndex, columnIndex + 1);
        cell.value = typeof value === 'number' ? value : safeText(value);
        cell.font = font();
        cell.alignment = {
          vertical: 'top',
          horizontal: columnIndex >= 1 && columnIndex <= 4 ? 'right' : 'left',
          wrapText: true,
        };
        cell.border = ALL_BORDERS;
      });
      rowIndex += 1;
    }
  }

  sheet.views = [{ state: 'frozen', ySplit: headerRow }];
  sheet.autoFilter = {
    from: { row: headerRow, column: 1 },
    to: { row: headerRow, column: 12 },
  };
  sheet.pageSetup.printTitlesRow = `${headerRow}:${headerRow}`;
  setFooter(sheet, dataset);
}

function createVerificationSheet(workbook: Workbook, dataset: CatalogExportDataset) {
  const sheet = workbook.addWorksheet('ข้อมูลตรวจสอบ', {
    pageSetup: landscapePageSetup(),
    properties: { tabColor: { argb: 'FFB91C1C' } },
  });
  const headers = verificationSheetHeaders();
  sheet.columns = [
    { width: 38 },
    { width: 18 },
    { width: 64 },
    { width: 10 },
    { width: 16 },
    { width: 16 },
    { width: 16 },
    { width: 20 },
    { width: 28 },
    { width: 18 },
    { width: 28 },
    { width: 18 },
    { width: 28 },
    { width: 12 },
    { width: 14 },
    { width: 120 },
  ];

  writeHeaderRow(sheet, 1, headers);
  dataset.rows.forEach((row, index) => {
    const rowIndex = index + 2;
    const values = [
      row.canonicalRow.identity_id,
      row.canonicalRow.item_code,
      row.canonicalRow.item_name,
      row.canonicalRow.unit,
      row.canonicalRow.material_cost,
      row.canonicalRow.labor_cost,
      row.canonicalRow.unit_cost,
      nullableJsonText(row.canonicalRow.category_code),
      nullableJsonText(row.canonicalRow.category_name),
      nullableJsonText(row.canonicalRow.work_context_code),
      nullableJsonText(row.canonicalRow.work_context_name_th),
      nullableJsonText(row.canonicalRow.item_type_code),
      nullableJsonText(row.canonicalRow.item_type_name_th),
      row.canonicalRow.is_active ? 'true' : 'false',
      row.canonicalRow.display_order,
      row.canonicalRowJson,
    ];

    values.forEach((value, columnIndex) => {
      const cell = sheet.getCell(rowIndex, columnIndex + 1);
      cell.value = value;
      cell.font = font({ size: 11 });
      cell.alignment = { vertical: 'top', wrapText: columnIndex === 2 || columnIndex === 15 };
      cell.border = ALL_BORDERS;
      if (columnIndex === 14) {
        cell.alignment = { horizontal: 'right', vertical: 'top' };
      }
    });
  });

  sheet.views = [{ state: 'frozen', ySplit: 1 }];
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: headers.length },
  };
  sheet.pageSetup.printTitlesRow = '1:1';
  setFooter(sheet, dataset);
}

function writePriceRow(sheet: Worksheet, rowIndex: number, row: CatalogExportRow) {
  const values = [
    row.sequence,
    row.itemCode,
    row.itemName,
    row.unit,
    row.materialCost,
    row.laborCost,
    row.unitCost,
    row.categoryName ?? row.categoryCode ?? '',
    row.workContextCode ?? '',
    row.workContextNameTh ?? '',
    row.itemTypeCode ?? '',
    row.itemTypeNameTh ?? '',
    row.isActive ? 'ใช้งาน' : 'ยกเลิกใช้',
  ];

  values.forEach((value, index) => {
    const cell = sheet.getCell(rowIndex, index + 1);
    cell.value = typeof value === 'string' ? safeText(value) : value;
    cell.font = font();
    cell.border = ALL_BORDERS;
    cell.alignment = {
      vertical: 'top',
      horizontal: index === 0 || index === 3 ? 'center' : index >= 4 && index <= 6 ? 'right' : 'left',
      wrapText: index === 2 || index === 7 || index === 9 || index === 11,
    };

    if (index >= 4 && index <= 6) {
      cell.numFmt = MONEY_FORMAT;
    }
  });
}

function writeHeaderRow(sheet: Worksheet, rowIndex: number, headers: readonly string[]) {
  headers.forEach((header, index) => {
    const cell = sheet.getCell(rowIndex, index + 1);
    cell.value = header;
    applyHeaderCellStyle(cell);
  });
}

function applyHeaderCellStyle(cell: Cell) {
  cell.font = font({ bold: true });
  cell.fill = HEADER_FILL;
  cell.border = ALL_BORDERS;
  cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
}

function styleKeyValueRow(sheet: Worksheet, rowIndex: number, fill: Fill = SUBTLE_FILL) {
  const keyCell = sheet.getCell(rowIndex, 1);
  const valueCell = sheet.getCell(rowIndex, 2);
  keyCell.font = font({ bold: true });
  valueCell.font = font();
  keyCell.fill = fill;
  keyCell.alignment = { vertical: 'top', wrapText: true };
  valueCell.alignment = { vertical: 'top', wrapText: true };
  keyCell.border = ALL_BORDERS;
  valueCell.border = ALL_BORDERS;
}

function styleDataRow(sheet: Worksheet, rowIndex: number, columns: number) {
  for (let column = 1; column <= columns; column += 1) {
    const cell = sheet.getCell(rowIndex, column);
    cell.font = font();
    cell.border = ALL_BORDERS;
    cell.alignment = { vertical: 'top', wrapText: true };
  }
}

function setFooter(sheet: Worksheet, dataset: CatalogExportDataset) {
  const statusOrDate = dataset.isDraftExport
    ? 'Draft'
    : dataset.version.effectiveDate
      ? formatThaiDate(dataset.version.effectiveDate)
      : displayStatus(dataset);
  sheet.headerFooter.oddFooter =
    `&Lฝ่ายท่อร้อยสาย (ทฐฐ.)&CPage &P of &N&Rv${dataset.version.versionString} | ${statusOrDate}`;
  sheet.headerFooter.evenFooter = sheet.headerFooter.oddFooter;
}

function portraitPageSetup() {
  return {
    paperSize: 9,
    orientation: 'portrait' as const,
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: { left: 0.45, right: 0.45, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.25 },
  };
}

function landscapePageSetup() {
  return {
    paperSize: 9,
    orientation: 'landscape' as const,
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: { left: 0.35, right: 0.35, top: 0.45, bottom: 0.45, header: 0.2, footer: 0.25 },
  };
}

function font(options: {
  bold?: boolean;
  italic?: boolean;
  size?: number;
  color?: string;
} = {}) {
  return {
    name: DEFAULT_FONT,
    family: 4,
    scheme: 'minor' as const,
    size: options.size ?? 13,
    bold: options.bold,
    italic: options.italic,
    color: options.color ? { argb: options.color } : undefined,
  };
}

function totalActionCounts(dataset: CatalogExportDataset): CatalogExportChangeActionCounts {
  return dataset.changeSets.reduce(
    (counts, changeSet) => ({
      add: counts.add + changeSet.itemActionCounts.add,
      update: counts.update + changeSet.itemActionCounts.update,
      retire: counts.retire + changeSet.itemActionCounts.retire,
      recode: counts.recode + changeSet.itemActionCounts.recode,
    }),
    { add: 0, update: 0, retire: 0, recode: 0 },
  );
}

function safeText(value: string): string {
  if (/^[=+\-@\t\r]/.test(value)) {
    return `'${value}`;
  }

  return value;
}

function nullableJsonText(value: string | null): string {
  return value === null ? 'null' : value;
}

function displayStatus(dataset: CatalogExportDataset): string {
  if (dataset.version.status === 'draft') return 'Draft';
  const defaultText = dataset.version.isCurrentDefault ? 'Yes' : 'No';
  return `${dataset.version.status === 'active' ? 'Published' : 'Archived'} | Current Default: ${defaultText}`;
}

function displayDateWithIso(value: string | null): string {
  if (!value) return '-';
  return `${formatThaiDate(value)} (${value})`;
}

function displayPublishedStamp(dataset: CatalogExportDataset): string {
  if (!dataset.version.publishedAt && !dataset.version.publishedByDisplayName) {
    return '-';
  }

  return `${formatThaiDateTime(dataset.version.publishedAt)} / ${dataset.version.publishedByDisplayName ?? '-'}`;
}

function formatThaiDate(value: string): string {
  return new Intl.DateTimeFormat('th-TH', {
    timeZone: 'Asia/Bangkok',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  }).format(new Date(`${value.slice(0, 10)}T00:00:00+07:00`));
}

function formatThaiDateTime(value: string | null): string {
  if (!value) return '-';
  return new Intl.DateTimeFormat('th-TH', {
    timeZone: 'Asia/Bangkok',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(value));
}
